const data = [
    {
        row : "Q",
        index : 0,
        seats : [
            { pos : 1, status : "empty", isSelected : false, type : "premium"},
            { pos : 2, status : "empty", isSelected : false, type : "premium"},
            { pos : 3, status : "empty", isSelected : false, type : "premium"},
            { pos : 4, status : "available", isSelected : false, type : "premium"},
            { pos : 5, status : "available", isSelected : false, type : "premium"},
            { pos : 6, status : "empty", isSelected : false, type : "premium"},
            { pos : 7, status : "unavailable", isSelected : false, type : "premium"},
            { pos : 8, status : "unavailable", isSelected : false, type : "premium"},
            { pos : 9, status : "empty", isSelected : false, type : "premium"},
            { pos : 10, status : "unavailable", isSelected : false, type : "premium"},
            { pos : 11, status : "unavailable", isSelected : false, type : "premium"},
            { pos : 12, status : "empty", isSelected : false, type : "premium"},
            { pos : 13, status : "available", isSelected : false, type : "premium"},
            { pos : 14, status : "available", isSelected : false, type : "premium"},
            { pos : 15, status : "empty", isSelected : false, type : "premium"},
            { pos : 16, status : "available", isSelected : false, type : "premium"},
            { pos : 17, status : "available", isSelected : false, type : "premium"},
            { pos : 18, status : "empty", isSelected : false, type : "premium"},
            { pos : 19, status : "available", isSelected : false, type : "premium"},
            { pos : 20, status : "available", isSelected : false, type : "premium"},
            { pos : 21, status : "empty", isSelected : false, type : "premium"},
            { pos : 22, status : "available", isSelected : false, type : "premium"},
            { pos : 23, status : "available", isSelected : false, type : "premium"},
            { pos : 24, status : "empty", isSelected : false, type : "premium"},
            { pos : 25, status : "empty", isSelected : false, type : "premium"}
        ]
    },
    {
        row : "P",
        index : 1,
        seats : [
            { pos : 1, status : "empty", isSelected : false, type : "premium"},
            { pos : 2, status : "empty", isSelected : false, type : "premium"},
            { pos : 3, status : "empty", isSelected : false, type : "premium"},
            { pos : 4, status : "unavailable", isSelected : false, type : "premium"},
            { pos : 5, status : "unavailable", isSelected : false, type : "premium"},
            { pos : 6, status : "empty", isSelected : false, type : "premium"},
            { pos : 7, status : "available", isSelected : false, type : "premium"},
            { pos : 8, status : "available", isSelected : false, type : "premium"},
            { pos : 9, status : "empty", isSelected : false, type : "premium"},
            { pos : 10, status : "available", isSelected : false, type : "premium"},
            { pos : 11, status : "available", isSelected : false, type : "premium"},
            { pos : 12, status : "empty", isSelected : false, type : "premium"},
            { pos : 13, status : "available", isSelected : false, type : "premium"},
            { pos : 14, status : "available", isSelected : false, type : "premium"},
            { pos : 15, status : "empty", isSelected : false, type : "premium"},
            { pos : 16, status : "unavailable", isSelected : false, type : "premium"},
            { pos : 17, status : "unavailable", isSelected : false, type : "premium"},
            { pos : 18, status : "empty", isSelected : false, type : "premium"},
            { pos : 19, status : "empty", isSelected : false, type : "premium"},
            { pos : 20, status : "available", isSelected : false, type : "premium"},
            { pos : 21, status : "available", isSelected : false, type : "premium"},
            { pos : 22, status : "empty", isSelected : false, type : "premium"},
            { pos : 23, status : "available", isSelected : false, type : "premium"},
            { pos : 24, status : "available", isSelected : false, type : "premium"},
            { pos : 25, status : "empty", isSelected : false, type : "premium"}
        ]
    },
    {
        row : "N",
        index : 2,
        seats : [
            { pos : 1, status : "empty", isSelected : false, type : "standard"},
            { pos : 2, status : "empty", isSelected : false, type : "standard"},
            { pos : 3, status : "empty", isSelected : false, type : "standard"},
            { pos : 4, status : "empty", isSelected : false, type : "standard"},
            { pos : 5, status : "unavailable", isSelected : false, type : "standard"},
            { pos : 6, status : "unavailable", isSelected : false, type : "standard"},
            { pos : 7, status : "available", isSelected : false, type : "standard"},
            { pos : 8, status : "available", isSelected : false, type : "standard"},
            { pos : 9, status : "unavailable", isSelected : false, type : "standard"},
            { pos : 10, status : "unavailable", isSelected : false, type : "standard"},
            { pos : 11, status : "unavailable", isSelected : false, type : "standard"},
            { pos : 12, status : "unavailable", isSelected : false, type : "standard"},
            { pos : 13, status : "available", isSelected : false, type : "standard"},
            { pos : 14, status : "available", isSelected : false, type : "standard"},
            { pos : 15, status : "available", isSelected : false, type : "standard"},
            { pos : 16, status : "available", isSelected : false, type : "standard"},
            { pos : 17, status : "available", isSelected : false, type : "standard"},
            { pos : 18, status : "available", isSelected : false, type : "standard"},
            { pos : 19, status : "empty", isSelected : false, type : "standard"},
            { pos : 20, status : "available", isSelected : false, type : "standard"},
            { pos : 21, status : "available", isSelected : false, type : "standard"},
            { pos : 22, status : "available", isSelected : false, type : "standard"},
            { pos : 23, status : "available", isSelected : false, type : "standard"},
            { pos : 24, status : "unavailable", isSelected : false, type : "standard"},
            { pos : 25, status : "unavailable", isSelected : false, type : "standard"}
        ]
    },
    {
        row : "M",
        index : 3,
        seats : [
            { pos : 1, status : "empty", isSelected : false, type : "standard"},
            { pos : 2, status : "empty", isSelected : false, type : "standard"},
            { pos : 3, status : "empty", isSelected : false, type : "standard"},
            { pos : 4, status : "empty", isSelected : false, type : "standard"},
            { pos : 5, status : "available", isSelected : false, type : "standard"},
            { pos : 6, status : "available", isSelected : false, type : "standard"},
            { pos : 7, status : "available", isSelected : false, type : "standard"},
            { pos : 8, status : "available", isSelected : false, type : "standard"},
            { pos : 9, status : "available", isSelected : false, type : "standard"},
            { pos : 10, status : "available", isSelected : false, type : "standard"},
            { pos : 11, status : "available", isSelected : false, type : "standard"},
            { pos : 12, status : "available", isSelected : false, type : "standard"},
            { pos : 13, status : "available", isSelected : false, type : "standard"},
            { pos : 14, status : "available", isSelected : false, type : "standard"},
            { pos : 15, status : "available", isSelected : false, type : "standard"},
            { pos : 16, status : "unavailable", isSelected : false, type : "standard"},
            { pos : 17, status : "unavailable", isSelected : false, type : "standard"},
            { pos : 18, status : "unavailable", isSelected : false, type : "standard"},
            { pos : 19, status : "empty", isSelected : false, type : "standard"},
            { pos : 20, status : "unavailable", isSelected : false, type : "standard"},
            { pos : 21, status : "unavailable", isSelected : false, type : "standard"},
            { pos : 22, status : "available", isSelected : false, type : "standard"},
            { pos : 23, status : "available", isSelected : false, type : "standard"},
            { pos : 24, status : "available", isSelected : false, type : "standard"},
            { pos : 25, status : "available", isSelected : false, type : "standard"}
        ]
    },
    {
        row : "L",
        index : 4,
        seats : [
            { pos : 1, status : "empty", isSelected : false, type : "standard"},
            { pos : 2, status : "empty", isSelected : false, type : "standard"},
            { pos : 3, status : "empty", isSelected : false, type : "standard"},
            { pos : 4, status : "empty", isSelected : false, type : "standard"},
            { pos : 5, status : "available", isSelected : false, type : "standard"},
            { pos : 6, status : "available", isSelected : false, type : "standard"},
            { pos : 7, status : "available", isSelected : false, type : "standard"},
            { pos : 8, status : "available", isSelected : false, type : "standard"},
            { pos : 9, status : "available", isSelected : false, type : "standard"},
            { pos : 10, status : "available", isSelected : false, type : "standard"},
            { pos : 11, status : "available", isSelected : false, type : "standard"},
            { pos : 12, status : "available", isSelected : false, type : "standard"},
            { pos : 13, status : "available", isSelected : false, type : "standard"},
            { pos : 14, status : "available", isSelected : false, type : "standard"},
            { pos : 15, status : "available", isSelected : false, type : "standard"},
            { pos : 16, status : "available", isSelected : false, type : "standard"},
            { pos : 17, status : "available", isSelected : false, type : "standard"},
            { pos : 18, status : "available", isSelected : false, type : "standard"},
            { pos : 19, status : "empty", isSelected : false, type : "standard"},
            { pos : 20, status : "available", isSelected : false, type : "standard"},
            { pos : 21, status : "available", isSelected : false, type : "standard"},
            { pos : 22, status : "available", isSelected : false, type : "standard"},
            { pos : 23, status : "available", isSelected : false, type : "standard"},
            { pos : 24, status : "available", isSelected : false, type : "standard"},
            { pos : 25, status : "available", isSelected : false, type : "standard"}
        ]
    },
    {
        row : "K",
        index : 5,
        seats : [
            { pos : 1, status : "empty", isSelected : false, type : "standard"},
            { pos : 2, status : "empty", isSelected : false, type : "standard"},
            { pos : 3, status : "empty", isSelected : false, type : "standard"},
            { pos : 4, status : "empty", isSelected : false, type : "standard"},
            { pos : 5, status : "available", isSelected : false, type : "standard"},
            { pos : 6, status : "available", isSelected : false, type : "standard"},
            { pos : 7, status : "available", isSelected : false, type : "standard"},
            { pos : 8, status : "available", isSelected : false, type : "standard"},
            { pos : 9, status : "available", isSelected : false, type : "standard"},
            { pos : 10, status : "available", isSelected : false, type : "standard"},
            { pos : 11, status : "available", isSelected : false, type : "standard"},
            { pos : 12, status : "available", isSelected : false, type : "standard"},
            { pos : 13, status : "available", isSelected : false, type : "standard"},
            { pos : 14, status : "available", isSelected : false, type : "standard"},
            { pos : 15, status : "available", isSelected : false, type : "standard"},
            { pos : 16, status : "available", isSelected : false, type : "standard"},
            { pos : 17, status : "available", isSelected : false, type : "standard"},
            { pos : 18, status : "available", isSelected : false, type : "standard"},
            { pos : 19, status : "empty", isSelected : false, type : "standard"},
            { pos : 20, status : "available", isSelected : false, type : "standard"},
            { pos : 21, status : "available", isSelected : false, type : "standard"},
            { pos : 22, status : "available", isSelected : false, type : "standard"},
            { pos : 23, status : "available", isSelected : false, type : "standard"},
            { pos : 24, status : "available", isSelected : false, type : "standard"},
            { pos : 25, status : "available", isSelected : false, type : "standard"}
        ]
    },
    {
        row : "J",
        index : 6,
        seats : [
            { pos : 1, status : "empty", isSelected : false, type : "standard"},
            { pos : 2, status : "empty", isSelected : false, type : "standard"},
            { pos : 3, status : "empty", isSelected : false, type : "standard"},
            { pos : 4, status : "empty", isSelected : false, type : "standard"},
            { pos : 5, status : "available", isSelected : false, type : "standard"},
            { pos : 6, status : "available", isSelected : false, type : "standard"},
            { pos : 7, status : "available", isSelected : false, type : "standard"},
            { pos : 8, status : "available", isSelected : false, type : "standard"},
            { pos : 9, status : "available", isSelected : false, type : "standard"},
            { pos : 10, status : "available", isSelected : false, type : "standard"},
            { pos : 11, status : "available", isSelected : false, type : "standard"},
            { pos : 12, status : "available", isSelected : false, type : "standard"},
            { pos : 13, status : "available", isSelected : false, type : "standard"},
            { pos : 14, status : "available", isSelected : false, type : "standard"},
            { pos : 15, status : "available", isSelected : false, type : "standard"},
            { pos : 16, status : "available", isSelected : false, type : "standard"},
            { pos : 17, status : "available", isSelected : false, type : "standard"},
            { pos : 18, status : "available", isSelected : false, type : "standard"},
            { pos : 19, status : "empty", isSelected : false, type : "standard"},
            { pos : 20, status : "available", isSelected : false, type : "standard"},
            { pos : 21, status : "available", isSelected : false, type : "standard"},
            { pos : 22, status : "available", isSelected : false, type : "standard"},
            { pos : 23, status : "available", isSelected : false, type : "standard"},
            { pos : 24, status : "available", isSelected : false, type : "standard"},
            { pos : 25, status : "available", isSelected : false, type : "standard"}
        ]
    },
    {
        row : "H",
        index : 7,
        seats : [
            { pos : 1, status : "unavailable", isSelected : false, type : "standard"},
            { pos : 2, status : "unavailable", isSelected : false, type : "standard"},
            { pos : 3, status : "unavailable", isSelected : false, type : "standard"},
            { pos : 4, status : "empty", isSelected : false, type : "standard"},
            { pos : 5, status : "available", isSelected : false, type : "standard"},
            { pos : 6, status : "available", isSelected : false, type : "standard"},
            { pos : 7, status : "available", isSelected : false, type : "standard"},
            { pos : 8, status : "available", isSelected : false, type : "standard"},
            { pos : 9, status : "available", isSelected : false, type : "standard"},
            { pos : 10, status : "available", isSelected : false, type : "standard"},
            { pos : 11, status : "available", isSelected : false, type : "standard"},
            { pos : 12, status : "available", isSelected : false, type : "standard"},
            { pos : 13, status : "available", isSelected : false, type : "standard"},
            { pos : 14, status : "available", isSelected : false, type : "standard"},
            { pos : 15, status : "available", isSelected : false, type : "standard"},
            { pos : 16, status : "available", isSelected : false, type : "standard"},
            { pos : 17, status : "available", isSelected : false, type : "standard"},
            { pos : 18, status : "available", isSelected : false, type : "standard"},
            { pos : 19, status : "empty", isSelected : false, type : "standard"},
            { pos : 20, status : "available", isSelected : false, type : "standard"},
            { pos : 21, status : "available", isSelected : false, type : "standard"},
            { pos : 22, status : "available", isSelected : false, type : "standard"},
            { pos : 23, status : "available", isSelected : false, type : "standard"},
            { pos : 24, status : "available", isSelected : false, type : "standard"},
            { pos : 25, status : "available", isSelected : false, type : "standard"}
        ]
    },
    {
        row : "G",
        index : 8,
        seats : [
            { pos : 1, status : "unavailable", isSelected : false, type : "standard"},
            { pos : 2, status : "unavailable", isSelected : false, type : "standard"},
            { pos : 3, status : "unavailable", isSelected : false, type : "standard"},
            { pos : 4, status : "empty", isSelected : false, type : "standard"},
            { pos : 5, status : "available", isSelected : false, type : "standard"},
            { pos : 6, status : "available", isSelected : false, type : "standard"},
            { pos : 7, status : "available", isSelected : false, type : "standard"},
            { pos : 8, status : "available", isSelected : false, type : "standard"},
            { pos : 9, status : "available", isSelected : false, type : "standard"},
            { pos : 10, status : "available", isSelected : false, type : "standard"},
            { pos : 11, status : "available", isSelected : false, type : "standard"},
            { pos : 12, status : "available", isSelected : false, type : "standard"},
            { pos : 13, status : "available", isSelected : false, type : "standard"},
            { pos : 14, status : "available", isSelected : false, type : "standard"},
            { pos : 15, status : "available", isSelected : false, type : "standard"},
            { pos : 16, status : "available", isSelected : false, type : "standard"},
            { pos : 17, status : "available", isSelected : false, type : "standard"},
            { pos : 18, status : "available", isSelected : false, type : "standard"},
            { pos : 19, status : "empty", isSelected : false, type : "standard"},
            { pos : 20, status : "available", isSelected : false, type : "standard"},
            { pos : 21, status : "available", isSelected : false, type : "standard"},
            { pos : 22, status : "available", isSelected : false, type : "standard"},
            { pos : 23, status : "available", isSelected : false, type : "standard"},
            { pos : 24, status : "available", isSelected : false, type : "standard"},
            { pos : 25, status : "available", isSelected : false, type : "standard"}
        ]
    },
    {
        row : "F",
        index : 9,
        seats : [
            { pos : 1, status : "empty", isSelected : false, type : "standard"},
            { pos : 2, status : "empty", isSelected : false, type : "standard"},
            { pos : 3, status : "empty", isSelected : false, type : "standard"},
            { pos : 4, status : "empty", isSelected : false, type : "standard"},
            { pos : 5, status : "available", isSelected : false, type : "standard"},
            { pos : 6, status : "available", isSelected : false, type : "standard"},
            { pos : 7, status : "available", isSelected : false, type : "standard"},
            { pos : 8, status : "available", isSelected : false, type : "standard"},
            { pos : 9, status : "available", isSelected : false, type : "standard"},
            { pos : 10, status : "available", isSelected : false, type : "standard"},
            { pos : 11, status : "available", isSelected : false, type : "standard"},
            { pos : 12, status : "available", isSelected : false, type : "standard"},
            { pos : 13, status : "available", isSelected : false, type : "standard"},
            { pos : 14, status : "available", isSelected : false, type : "standard"},
            { pos : 15, status : "available", isSelected : false, type : "standard"},
            { pos : 16, status : "available", isSelected : false, type : "standard"},
            { pos : 17, status : "available", isSelected : false, type : "standard"},
            { pos : 18, status : "available", isSelected : false, type : "standard"},
            { pos : 19, status : "empty", isSelected : false, type : "standard"},
            { pos : 20, status : "available", isSelected : false, type : "standard"},
            { pos : 21, status : "available", isSelected : false, type : "standard"},
            { pos : 22, status : "available", isSelected : false, type : "standard"},
            { pos : 23, status : "available", isSelected : false, type : "standard"},
            { pos : 24, status : "available", isSelected : false, type : "standard"},
            { pos : 25, status : "available", isSelected : false, type : "standard"}
        ]
    },
    {
        row : "E",
        index : 10,
        seats : [
            { pos : 1, status : "empty", isSelected : false, type : "standard"},
            { pos : 2, status : "empty", isSelected : false, type : "standard"},
            { pos : 3, status : "empty", isSelected : false, type : "standard"},
            { pos : 4, status : "empty", isSelected : false, type : "standard"},
            { pos : 5, status : "available", isSelected : false, type : "standard"},
            { pos : 6, status : "available", isSelected : false, type : "standard"},
            { pos : 7, status : "available", isSelected : false, type : "standard"},
            { pos : 8, status : "available", isSelected : false, type : "standard"},
            { pos : 9, status : "available", isSelected : false, type : "standard"},
            { pos : 10, status : "available", isSelected : false, type : "standard"},
            { pos : 11, status : "available", isSelected : false, type : "standard"},
            { pos : 12, status : "available", isSelected : false, type : "standard"},
            { pos : 13, status : "available", isSelected : false, type : "standard"},
            { pos : 14, status : "available", isSelected : false, type : "standard"},
            { pos : 15, status : "available", isSelected : false, type : "standard"},
            { pos : 16, status : "available", isSelected : false, type : "standard"},
            { pos : 17, status : "available", isSelected : false, type : "standard"},
            { pos : 18, status : "available", isSelected : false, type : "standard"},
            { pos : 19, status : "empty", isSelected : false, type : "standard"},
            { pos : 20, status : "available", isSelected : false, type : "standard"},
            { pos : 21, status : "available", isSelected : false, type : "standard"},
            { pos : 22, status : "available", isSelected : false, type : "standard"},
            { pos : 23, status : "available", isSelected : false, type : "standard"},
            { pos : 24, status : "available", isSelected : false, type : "standard"},
            { pos : 25, status : "available", isSelected : false, type : "standard"}
        ]
    },
];

export default data;

